[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
lazy_static = "1.4.0"
log = "0.4.21"
strum = "0.26.2"
strum_macros = "0.26.2"
threadpool = "1.8.1"

[dev-dependencies]
rstest = "0.19.0"
